# Generated by Django 3.2.7 on 2021-11-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='calorie_intake',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
