# Generated by Django 3.2.7 on 2021-11-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211108_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
