# Generated by Django 3.2.7 on 2021-11-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20211108_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='posted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
