# Generated by Django 3.2.7 on 2021-11-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
